# Generated by Django 4.1.5 on 2023-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
