# Generated by Django 4.1.5 on 2023-02-06 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(null=True, verbose_name='id чата')),
                ('user_ud', models.BigIntegerField(null=True, verbose_name='id пользователя')),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)])),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код верификации')),
            ],
        ),
    ]
