# Generated by Django 4.1.5 on 2023-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(null=True, verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_ud',
            field=models.BigIntegerField(null=True, verbose_name='id пользователя'),
        ),
    ]
