# Generated by Django 4.1.5 on 2023-01-13 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_chat_id_alter_tguser_user_ud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(default='username', max_length=32, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
